---
title: Functional analysis
author: Sivan
date: '2023-09-14'
slug: []
categories: []
tags: []
---


### Over representation analysis


### Gene set enrichment analysis

GSEA is a method designed to assess whether a predefined set of genes shows significant distribution patterns within a gene list ranked by its association with a phenotype. Rather than focusing solely on individual genes, it evaluates the collective prominence of a gene set at the top or bottom of the ranked list, inferring the set's overall contribution to the phenotype.

After conducting differential gene expression analysis and obtaining logFC values for each gene, these logFC values offer a ranking based on expression differences. By employing GSEA, you can determine if a predefined gene set, such as those from a specific biological process or pathway, is significantly enriched within your ranked list of differentially expressed genes. This assists in discerning functional and pathway differences between the two conditions.

The predefined gene sets originate from the MSigDB database (https://www.gsea-msigdb.org/gsea/msigdb/index.jsp). These sets predominantly consist of functional genes. If one only has non-functional genes (e.g., miRNA, lncRNA, circRNA), GSEA analysis might not be feasible due to the absence of appropriate gene sets.

### Gene set variation analysis

GSVA is a non-parametric, unsupervised analytical method primarily for evaluating gene set enrichment in microarrays and transcriptomes. It works by transforming gene expression matrices across samples into gene set expression matrices to assess the enrichment of metabolic pathways. GSVA quantifies gene set enrichment scores per sample, facilitating subsequent statistical analyses. Using the limma package, one can identify differentially expressed genes between samples. Similarly, applying limma to GSVA results (still a matrix) identifies significantly different gene sets. These differentially expressed gene sets, compared to individual genes, offer richer biological insights and interpretability, which can further aid in areas like tumor subtyping and other biologically-relevant inquiries

### Main takeaways


### References
https://string-db.org/cgi/network?taskId=bPOuuq42ucGt&sessionId=bLeXsbEr0ukN 

shinygo: http://impala.molgen.mpg.de/

goprofiler: https://biit.cs.ut.ee/gprofiler/page/r

heatmap: https://github.com/jokergoo/KeywordsEnrichment

gsva原理： https://www.pathwaycommons.org/guide/primers/data_analysis/gsea/